### PR TITLE
ci-operator: fix configuration access order

### LINKED ISSUE #877: Error while running tests locally
when trying to run tests locally I get the following error :
```
[irosenzw@IdoWork ci-tools]$ ./ci-operator --config openshift-console-master.yaml --git-ref openshift/console@master
2020/06/02 11:54:42 unset version 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x16b590c]

goroutine 1 [running]:
main.(*options).Complete(0xc00046a000, 0xc00061ff20, 0x4)
	/home/irosenzw/openshift-ci/ci-tools/cmd/ci-operator/main.go:374 +0x11c
main.main()
	/home/irosenzw/openshift-ci/ci-tools/cmd/ci-operator/main.go:196 +0x1f8
```

### PR DESCRIPTION
**Pull request by bbguimaraes**
Fixes #877.

### CODE REVIEW

File: cmd/ci-operator/main.go [hunk 1]
```diff
@@ -398,8 +398,10 @@ func (o *options) Complete() error {
 	if err != nil {
 		return results.ForReason("loading_config").WithError(err).Errorf("failed to load configuration: %v", err)
 	}
+	if config.CanonicalGoRepository != nil {
+		o.jobSpec.Refs.PathAlias = *config.CanonicalGoRepository
```
Comment (stevekuznetsov) [inline cmd/ci-operator/main.go:402]: Before, you set the PathAlias to `o.configSpec.CanonicalGoRepository`. Now, it's `config.CanonicalGoRepository`. Why?
